### ISSUE TITLE
Got error `AttributeError: 'Page' object has no attribute 'get_absolute_url'`

### ISSUE THREAD

**Issue by vkuzmov** [just-work/django-sitemap-generate#76]
What should I do to make it work? Very poor usage description :(

**Comment by tumb1er** [comment]
Very poor bug description)

Could you please at least Django version and complete traceback?

**Comment by vkuzmov** [comment]
Sure. Sorry about that.

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/sitemap-page.xml

Django Version: 5.0.6
Python Version: 3.12.4
Installed Applications:
['ckeditor',
 'ckeditor_uploader',
 'captcha',
 'blog',
 'demo_requests',
 'tenderalpha',
 'notifications',
 'jazzmin',
 'alerts',
 'visits',
 'careers',
 'cms',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django_cleanup.apps.CleanupConfig',
 'django_cool_paginator',
 'maintenance_mode',
 'adminsortable2',
 'sitemap_generate']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'maintenance_mode.middleware.MaintenanceModeMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 23, in inner
    response = func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/sitemaps/views.py", line 117, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 104, in get_urls
    return self._urls(page, protocol, domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 124, in _urls
    loc = f"{protocol}://{domain}{self._location(item)}"
                                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 69, in _location
    return self._get("location", item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 39, in _get
    return attr(item)
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/contrib/sitemaps/__init__.py", line 79, in location
    return item.get_absolute_url()
           ^^^^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /sitemap-page.xml
Exception Value: 'Page' object has no attribute 'get_absolute_url'
```

Page model definition

```python
class Page(models.Model):
     ...
```

**Comment by vkuzmov** [comment]
IMO, the problem is that by default models are not aware of that `get_absolute_url()` method. Is that related to [sites framework](https://docs.djangoproject.com/en/5.0/ref/contrib/sites/#module-django.contrib.sites)?

**Comment by tumb1er** [comment]
https://docs.djangoproject.com/en/5.0/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.location
You can either add `Sitemap.location` method for page sitemap or implement `Page.get_absolute_url`.

**Comment by vkuzmov** [comment]
Yep. It works. Thanks :) 

I found [this article](https://reintech.io/blog/creating-a-custom-sitemap-generator-in-django) helpful. At least they tell me where should I put each piece of code :)

**Comment by tumb1er** [comment]
:+1:
