### ISSUE TITLE
KeyError: 'wsgi.url_scheme'

### ISSUE THREAD

**Issue by kpy21ui** [just-work/django-sitemap-generate#8]
While trying to generate sitemap an error has occurred
```
>>>generator = SitemapGenerator(sitemaps=sitemaps)
>>>generator.generate()


  File "/usr/local/lib/python3.8/site-packages/sitemap_generate/generator.py", line 110, in generate
    index_content = self.fetch_content(url)
  File "/usr/local/lib/python3.8/site-packages/sitemap_generate/generator.py", line 96, in fetch_content
    return self.recorder.record(url)
  File "/usr/local/lib/python3.8/site-packages/sitemap_generate/generator.py", line 59, in record
    content = b''.join(self.wsgi(environ, self._start_response))
  File "/usr/local/lib/python3.8/site-packages/raven/middleware.py", line 98, in __call__
    self.client.http_context(self.get_http_context(environ))
  File "/usr/local/lib/python3.8/site-packages/raven/middleware.py", line 106, in get_http_context
    'url': get_current_url(environ, strip_querystring=True),
  File "/usr/local/lib/python3.8/site-packages/raven/utils/wsgi.py", line 81, in get_current_url
    tmp = [environ['wsgi.url_scheme'], '://', get_host(environ)]
KeyError: 'wsgi.url_scheme'
```

**Comment by tumb1er** [comment]
Hello. Seems that sentry requires this variable. 
[PEP-333](https://www.python.org/dev/peps/pep-0333/) has a list of WSGI required variables, so it's defenitely a bug.

**Comment by kpy21ui** [comment]
Thank you for a quick answer. Can I make like that:

```
environ = {
    ...
    'wsgi.url_scheme': defaults.SITEMAP_PROTO
}
```

or we should use another variable for this?

**Comment by kpy21ui** [comment]
I've faced with another one problem related to `Sentry` and `environ['SERVER_PORT']`. Could I extend this issue or create a separated one for that? 

an error example
`generate_sitemap_task()
[none] INFO 2020-07-30 16:29:16,590 base 1 139650246303048 Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/opt/project/src/offer/tasks.py", line 212, in generate_sitemap_task
    generator.generate()
  File "/usr/local/lib/python3.8/site-packages/sitemap_generate/generator.py", line 110, in generate
    index_content = self.fetch_content(url)
  File "/usr/local/lib/python3.8/site-packages/sitemap_generate/generator.py", line 96, in fetch_content
    return self.recorder.record(url)
  File "/usr/local/lib/python3.8/site-packages/sitemap_generate/generator.py", line 59, in record
    content = b''.join(self.wsgi(environ, self._start_response))
  File "/usr/local/lib/python3.8/site-packages/raven/middleware.py", line 98, in __call__
    self.client.http_context(self.get_http_context(environ))
  File "/usr/local/lib/python3.8/site-packages/raven/middleware.py", line 106, in get_http_context
    'url': get_current_url(environ, strip_querystring=True),
  File "/usr/local/lib/python3.8/site-packages/raven/utils/wsgi.py", line 81, in get_current_url
    tmp = [environ['wsgi.url_scheme'], '://', get_host(environ)]
  File "/usr/local/lib/python3.8/site-packages/raven/utils/wsgi.py", line 51, in get_host
    result += ':' + environ['SERVER_PORT']
TypeError: can only concatenate str (not "int") to str`

**Comment by tumb1er** [comment]
> Could I extend this issue or create a separated one for that?

I think all these errors should be fixed together as "PEP-333 compliance". And PR is welcome. 

BTW, may django test request factory be useful for all this stuff?

**Comment by kpy21ui** [comment]
> > Could I extend this issue or create a separated one for that?
> 
> I think all these errors should be fixed together as "PEP-333 compliance". And PR is welcome.
> 
> BTW, may django test request factory be useful for all this stuff?

**Comment by kpy21ui** [comment]
@tumb1er I can't push my branch in this repo. I've got "Permission denied" error

**Comment by tumb1er** [comment]
@kpy21ui push branch to your fork and than create a pull-request
